# Generated by Django 2.1.7 on 2019-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='chat_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
