# Generated by Django 2.1.7 on 2019-03-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_data', '0002_auto_20190312_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Todo',
        ),
    ]
